window.isMobile=!1;if(/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)){window.isMobile=!0}
function t_throttle(fn,threshhold,scope){var last;var deferTimer;threshhold||(threshhold=250);return function(){var context=scope||this;var now=+new Date();var args=arguments;if(last&&now<last+threshhold){clearTimeout(deferTimer);deferTimer=setTimeout(function(){last=now;fn.apply(context,args)},threshhold)}else{last=now;fn.apply(context,args)}}}
function t635_init(recid,textColor,cursorColor){var rec=document.querySelector('#rec'+recid);if(!rec)return;var typingData=rec.querySelector('.t635__textholder');if(!typingData)return;var typingRecIdList=typingData.getAttribute('data-recid').split(',');if(typingRecIdList.length===0)return;typingRecIdList.forEach(function(animRecId){var currentRecID=document.querySelector('#rec'+animRecId);if(!currentRecID)return;var screenMin=parseInt(currentRecID.getAttribute('data-screen-min'),10);var screenMax=parseInt(currentRecID.getAttribute('data-screen-max'),10);if(isNaN(screenMax)&&isNaN(screenMin)){t635_startType(recid,animRecId,textColor,cursorColor)}else if(!isNaN(screenMax)&&!isNaN(screenMin)){if(window.innerWidth>=screenMin&&window.innerWidth<=screenMax){t635_startType(recid,animRecId,textColor,cursorColor)}}else if(!isNaN(screenMax)){if(window.innerWidth<=screenMax){t635_startType(recid,animRecId,textColor,cursorColor)}}else if(!isNaN(screenMin)){if(window.innerWidth>=screenMin){t635_startType(recid,animRecId,textColor,cursorColor)}}})}
function t635_startType(recid,animRecId,textColor,cursorColor){var rec=document.querySelector('#rec'+recid);if(!rec)return;var animData=rec.querySelector('.t635__textholder');if(!animData)return;var animText=t635_findAnimElem(animRecId);var phrasesList=[];var phrase1=animData.getAttribute('data-text1');var phrase2=animData.getAttribute('data-text2');var phrase3=animData.getAttribute('data-text3');var phrase4=animData.getAttribute('data-text4');var phrase5=animData.getAttribute('data-text5');var animSpeed=animData.getAttribute('data-speed');var animLoop=animData.getAttribute('data-loop');var backspaceDelay=animData.getAttribute('data-backspacing-delay');if(!animText)return;if(typeof phrase1==='string'){phrasesList.push(phrase1.slice(0,80))}
if(typeof phrase2==='string'){phrasesList.push(phrase2.slice(0,80))}
if(typeof phrase3==='string'){phrasesList.push(phrase3.slice(0,80))}
if(typeof phrase4==='string'){phrasesList.push(phrase4.slice(0,80))}
if(typeof phrase5==='string'){phrasesList.push(phrase5.slice(0,80))}
if(animText&&phrasesList.length){var animTextHtml=animText.innerHTML;var animTextSplitted=animTextHtml.split('|');animText.innerHTML=animTextSplitted[0]+'<span class="t635__typing-text"></span>'+animTextSplitted[1];t635_updateAnimTextLimits(animRecId);t_onFuncLoad('t_throttle',function(){window.addEventListener('resize',t_throttle(function(){t635_updateAnimTextLimits(animRecId)}))});setInterval(function(){t635_updateAnimTextLimits(animRecId)},5000);var animatedText=document.querySelector('#rec'+animRecId+' .t635__typing-text');var animTextTop=animatedText.getAttribute('data-top-limit');var animTextBottom=animatedText.getAttribute('data-bottom-limit');var windowTop=document.querySelector('html').scrollTop;var windowBottom=windowTop+window.innerHeight;t_onFuncLoad('Typed',function(){var typedInstance=t635_animateText(animRecId,phrasesList,animSpeed,animLoop,backspaceDelay);var animatedCursor=document.querySelector('#rec'+animRecId+' .typed-cursor');if(textColor&&animatedText)animatedText.style.color=textColor;if(cursorColor&&animatedCursor)animatedCursor.style.color=cursorColor;if(animTextBottom<windowTop||animTextTop>windowBottom){typedInstance.reset();typedInstance.stop()}
t_onFuncLoad('t_throttle',function(){window.addEventListener('scroll',t_throttle(function(){animTextTop=animatedText.getAttribute('data-top-limit');animTextBottom=animatedText.getAttribute('data-bottom-limit');windowTop=document.querySelector('html').scrollTop;windowBottom=windowTop+window.innerHeight;if(animTextBottom<windowTop||animTextTop>windowBottom){typedInstance.reset();typedInstance.stop()}else{typedInstance.start()}},700))})})}}
function t635_findAnimElem(animRecId){var animRec=document.querySelector('#rec'+animRecId);if(!animRec)return;var currentH1=t635_findAnimTag(animRec,'h1');var currentH2=t635_findAnimTag(animRec,'h2');var currentH3=t635_findAnimTag(animRec,'h3');var currentDiv=t635_findAnimTag(animRec,'div');if(currentH1)return currentH1;if(currentH2)return currentH2;if(currentH3)return currentH3;if(currentDiv)return currentDiv}
function t635_findAnimTag(parent,element){var allElements=parent.querySelectorAll(element);for(var i=0;i<allElements.length;i++){if(allElements[i].innerHTML.indexOf('|')!==-1&&allElements[i].innerHTML.indexOf('t-map')===-1){var lastElement=allElements[i]}}
return lastElement}
function t635_updateAnimTextLimits(animRecId){var animatedBlock=document.querySelector('#rec'+animRecId);if(!animatedBlock)return;var animatedText=animatedBlock.querySelector('.t635__typing-text');if(animatedText){animatedText.setAttribute('data-top-limit',animatedText.getBoundingClientRect().top+window.pageYOffset);animatedText.setAttribute('data-bottom-limit',animatedBlock.getBoundingClientRect().top+window.pageYOffset+animatedBlock.clientHeight)}}
function t635_animateText(animRecId,phrasesList,animSpeed,animLoop,backspaceDelay){if(!animSpeed)animSpeed=40;if(!backspaceDelay)backspaceDelay=800;if(animLoop===null)animLoop=!0;if(animLoop==='false')animLoop=!1;var animRec='#rec'+animRecId+' .t635__typing-text';return new Typed(animRec,{strings:phrasesList,typeSpeed:animSpeed*1,startDelay:600,backDelay:backspaceDelay,loop:animLoop,})}
function t886_init(recid){var rec=document.querySelector('#rec'+recid);if(!rec)return;var notificationBlock=rec.querySelector('.t886');var closeButton=rec.querySelector('.t886__btn');var storageItem=notificationBlock.getAttribute('data-storage-item');var lastOpen=null;if(typeof localStorage==='object'){try{lastOpen=localStorage.getItem(storageItem)}catch(error){console.log('Your web browser does not support localStorage. Error status: ',error)}}
if(!lastOpen){notificationBlock.classList.remove('t886_closed')}
if(closeButton){closeButton.addEventListener('click',function(event){notificationBlock.classList.add('t886_closed');if(typeof localStorage==='object'){try{localStorage.setItem(storageItem,Math.floor(Date.now()/1000))}catch(error){console.log('Your web browser does not support localStorage. Error status: ',error)}}
event.preventDefault()})}}
function t450_showMenu(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var menu=rec.querySelector('.t450');var overlay=rec.querySelector('.t450__overlay');var menuElements=rec.querySelectorAll('.t450__overlay, .t450__close, a[href*="#"]');document.body.classList.add('t450__body_menushowed');if(menu)menu.classList.add('t450__menu_show');if(overlay)overlay.classList.add('t450__menu_show');if(menu){menu.addEventListener('clickedAnchorInTooltipMenu',function(){t450_closeMenu(menu,overlay)})}
Array.prototype.forEach.call(menuElements,function(element){element.addEventListener('click',function(){if(element.closest('.tooltipstered, .t-menusub__target-link, .t794__tm-link, .t966__tm-link, .t978__tm-link'))return;if(element.href&&(element.href.substring(0,7)==='#price:'||element.href.substring(0,9)==='#submenu:'))return;t450_closeMenu(menu,overlay)})});document.addEventListener('keydown',function(e){if(e.keyCode===27){document.body.classList.remove('t390__body_popupshowed');var popups=document.querySelectorAll('.t390');Array.prototype.forEach.call(popups,function(popup){popup.classList.remove('t390__popup_show')})}});rec.addEventListener('click',function(e){if(e.target.closest('.t966__tm-link, .t978__tm-link')){t450_checkSize(recid);if(e.target.closest('.t978__tm-link')){setTimeout(function(){var hookLink=e.target.closest('.t978__tm-link');var menuBlock=hookLink.nextElementSibling;var submenuLinks=menuBlock?menuBlock.querySelectorAll('.t978__menu-link'):[];Array.prototype.forEach.call(submenuLinks,function(link){link.addEventListener('click',function(){t450_checkSize(recid)})})},300)}}});t450_highlight(recid)}
function t450_closeMenu(menu,overlay){document.body.classList.remove('t450__body_menushowed');if(menu)menu.classList.remove('t450__menu_show');if(overlay)overlay.classList.remove('t450__menu_show')}
function t450_checkSize(recid){var rec=document.getElementById('rec'+recid);var menu=rec?rec.querySelector('.t450'):null;if(!menu)return;var container=menu.querySelector('.t450__container');var topContainer=menu.querySelector('.t450__top');var rightContainer=menu.querySelector('.t450__rightside');setTimeout(function(){var topContainerHeight=topContainer?topContainer.offsetHeight:0;var rightContainerHeight=rightContainer?rightContainer.offsetHeight:0;var containerPaddingTop=container?window.getComputedStyle(container).paddingTop:'0';var containerPaddingBottom=container?window.getComputedStyle(container).paddingBottom:'0';containerPaddingTop=parseInt(containerPaddingTop,10);containerPaddingBottom=parseInt(containerPaddingBottom,10);if(topContainerHeight+rightContainerHeight+containerPaddingTop+containerPaddingBottom>document.documentElement.clientHeight){menu.classList.add('t450__overflowed');if(container)container.style.height='auto'}else{menu.classList.remove('t450__overflowed');if(container)container.style.height=''}})}
function t450_appearMenu(recid){var rec=document.getElementById('rec'+recid);var burger=rec?rec.querySelector('.t450__menu__content'):null;if(!burger)return;var burgerAppearOffset=burger?burger.getAttribute('data-appearoffset'):'';var burgerHideOffset=burger?burger.getAttribute('data-hideoffset'):'';if(burgerAppearOffset){burgerAppearOffset=t450_appearMenuParseNumber(burgerAppearOffset);if(window.pageYOffset>=burgerAppearOffset){if(burger.classList.contains('t450__beforeready')){burger.classList.remove('t450__beforeready')}}else{burger.classList.add('t450__beforeready')}}
if(burgerHideOffset){burgerHideOffset=t450_appearMenuParseNumber(burgerHideOffset);var scrollHeight=Math.max(document.body.scrollHeight,document.documentElement.scrollHeight,document.body.offsetHeight,document.documentElement.offsetHeight,document.body.clientHeight,document.documentElement.clientHeight);if(window.pageYOffset+window.innerHeight>=scrollHeight-burgerHideOffset){if(!burger.classList.contains('t450__beforeready')){burger.classList.add('t450__beforeready')}}else if(burgerAppearOffset){if(window.pageYOffset>=burgerAppearOffset){burger.classList.remove('t450__beforeready')}}else{burger.classList.remove('t450__beforeready')}}}
function t450_appearMenuParseNumber(string){if(string.indexOf('vh')>-1){string=Math.floor((window.innerHeight*(parseInt(string)/100)))}
return parseInt(string,10)}
function t450_initMenu(recid){var rec=document.getElementById('rec'+recid);var menu=rec?rec.querySelector('.t450'):null;var overlay=rec?rec.querySelector('.t450__overlay'):null;var burger=rec?rec.querySelector('.t450__burger_container'):null;var menuLinks=rec?rec.querySelectorAll('.t-menu__link-item.t450__link-item_submenu'):[];var hook=menu?menu.getAttribute('data-tooltip-hook'):'';if(hook){document.addEventListener('click',function(e){if(e.target.closest('a[href="'+hook+'"]')){e.preventDefault();t450_closeMenu(menu,overlay);t450_showMenu(recid);t450_checkSize(recid)}})}
if(burger){burger.addEventListener('click',function(){t450_closeMenu(menu,overlay);t450_showMenu(recid);t450_checkSize(recid)})}
window.addEventListener('resize',function(){t450_checkSize(recid)});if(!window.isMobile)return;Array.prototype.forEach.call(menuLinks,function(link){link.addEventListener('click',function(){t450_checkSize(recid)})})}
function t450_highlight(recid){var url=window.location.href;var pathname=window.location.pathname;var hash=window.location.hash;if(url.substr(url.length-1)==='/'){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)==='/'){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)==='/'){pathname=pathname.slice(1)}
if(pathname===''){pathname='/'}
var shouldBeActiveElements=document.querySelectorAll('.t450__menu a[href=\''+url+'\'], '+'.t450__menu a[href=\''+url+'/\'], '+'.t450__menu a[href=\''+pathname+'\'], '+'.t450__menu a[href=\'/'+pathname+'\'], '+'.t450__menu a[href=\''+pathname+'/\'], '+'.t450__menu a[href=\'/'+pathname+'/\']'+(hash?', .t450__menu a[href=\''+hash+'\']':''));var rec=document.getElementById('rec'+recid);var menuLinks=rec?rec.querySelectorAll('.t450__menu a'):[];Array.prototype.forEach.call(menuLinks,function(link){link.classList.remove('t-active')});Array.prototype.forEach.call(shouldBeActiveElements,function(link){link.classList.add('t-active')})}